"""Add hashed_password to users

Revision ID: 8d4b5878d7a9
Revises: b7c4b476c821
Create Date: 2026-07-06 14:53:41.514638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4b5878d7a9'
down_revision: Union[str, Sequence[str], None] = 'b7c4b476c821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_foreign_key('users_customer_id_fkey', 'users', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_customer_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'customer_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
