"""Add telemetry diagnostics

Revision ID: b7c4b476c821
Revises: b347c3fda583
Create Date: 2026-07-06 00:50:42.823928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c4b476c821'
down_revision: Union[str, Sequence[str], None] = 'b347c3fda583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('hardware_version', sa.String(length=50), nullable=True))
    op.add_column('telemetry', sa.Column('boot_count', sa.Integer(), nullable=True))
    op.add_column('telemetry', sa.Column('uptime_seconds', sa.Integer(), nullable=True))
    op.add_column('telemetry', sa.Column('network_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_telemetry_device_id_timestamp_desc'), table_name='telemetry')
    op.create_index('ix_telemetry_device_id_timestamp_desc', 'telemetry', ['device_id', 'timestamp'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_device_id_timestamp_desc', table_name='telemetry', postgresql_using='btree')
    op.create_index(op.f('ix_telemetry_device_id_timestamp_desc'), 'telemetry', ['device_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_column('telemetry', 'network_type')
    op.drop_column('telemetry', 'uptime_seconds')
    op.drop_column('telemetry', 'boot_count')
    op.drop_column('telemetry', 'hardware_version')
    # ### end Alembic commands ###
